package org.evolution.model.trait

enum class TraitType {
    PREDATOR, FAT, AQUATIC,
    BURROWING, CAMOUFLAGE, SHARP_VISION,
    POISONOUS, RUNNING, SYMBIOSIS,
    PIRACY, COOPERATION, COMMUNICATION,
    SCAVENGER, LARGE, TRAMPLING,
    TAIL_LOSS, HIBERNATION, MIMICRY,
    PARASITE
}